- leaflet/__init__.py
Allows transparent https usage by default
> Use protocol independant url

- leaflet/forms/widgets.py
From the https://github.com/makinacorpus/django-leaflet/issues/123 issue
> Added slugged strings for accepting multi-word field name

- leaflet/__init__.py
- leaflet/forms/widgets.py
- leaflet/templates/leaflet/widget.html
- leaflet/templatetags/leaflet_tags.py
From the https://github.com/makinacorpus/django-leaflet/issues/125 issue
> Added 'loadevent' attribute to the widgets

- CHANGES
- README.rst
- leaflet/static/leaflet/leaflet.extras.js
> Allow an empty list as a setting for TILES

- leaflet/__init__.py
- leaflet/apps.py
- leaflet/tests/tests.py
- quicktest.py
fixes for Django 1.10 compatibility (#138)
> fixes for Django 1.10 compatibility (#138)

- leaflet/tests/tests.py
> Tests for a LeafletGeoAdminMixin

- leaflet/templates/leaflet/widget.html
Addresses similar issue as #42
> Fix localization issues in leaflet/widget.html

- leaflet/locale/de/LC_MESSAGES/django.po
Hey,
I have updated the german localization a little bit (only the .po files tho). Although I'm german not everything is perfect as it is sometimes strange to translate technical/geo stuff into german. But it's better than google translate i guess :)
Best regards,
Schumi
> Updated german localization

- leaflet/templates/leaflet/_leaflet_map.html
- leaflet/templates/leaflet/admin/widget.html
- leaflet/templates/leaflet/css.html
- leaflet/templates/leaflet/js.html
- leaflet/templates/leaflet/widget.html
{% load static from staticfiles %}
it is not compatible with django 1.11.14. 
Instead use {% load static %}
> changes in staticfiles for django 1.11.14

- example/requirements.txt
Get latest 1.11 django version and correct django-leaflet version
> Fix requirements in example

- docs/widget.rst
thanks to the reporter of issue #161, I only spent three hours, not three days, to work around the same problem.
this edit is an attempt to spare time to future users.
> help users with issue #161

- leaflet/__init__.py
These deprecations were added in 2013.
> Remove old deprecations

- docs/installation.rst
Document GDAL library dependency.
> Document GDAL dependency

- leaflet/locale/fa/LC_MESSAGES/django.po
persian/farsi translation of django-leaflet
> tranlate to persian

- leaflet/templates/leaflet/widget.html
Add `class` context variable to template to enable adding custom classes to input
> Update widget.html to add {{class}} context variable to input class

- leaflet/__init__.py
> Change DEFAULT_TILES attribution to HTTPS

- leaflet/__init__.py
- leaflet/utils.py
> Remove memoizing static URLs

- example/mushrooms/urls.py
- example/requirements.txt
Just a small PR to make the example project use Django 4 instead of Django 3.
> make example project use Django 4

- leaflet/forms/widgets.py
Remove debug print added in #371.
> Remove debug print added in #371

- leaflet/static/leaflet/draw/leaflet.draw.i18n.js
> Fix JS error if with-forms does not exists #379

- leaflet/static/leaflet/leaflet.extras.js
> Avoid defining imgPathElement globally

- leaflet/static/leaflet/draw/leaflet.draw.i18n.js
> Avoid defining withForms globally
