makinacorpus/django-leaflet

README.rst
leaflet/templates/leaflet/js.html
leaflet/templatetags/leaflet_tags.py

django-compressor, with the compression option turned on, renames included js files. This means that Leaflet can't use its own filename to determine the path to image files, see https://github.com/Leaflet/Leaflet/blob/5a518194945813f4b578861799f23a94248b553e/src/layer/marker/Icon.Default.js#L23-L25.
This edit adds a settings option `SET_IMAGE_PATH_MANUALLY`, which will cause the file path to be written manually at the end of the generated js includes:
``` js
L.Icon.Default.imagePath = "{% static "leaflet/images" %}";
```

deal with filename altering by e.g. django-compressor

---

CHANGES
leaflet/templatetags/leaflet_tags.py

Fixes `django.utils.functional.__proxy__ object is not JSON serializable` error on:
from django.utils.translation import ugettext_lazy as _
LEAFLET_CONFIG = {'ATTRIBUTION_PREFIX': _('Foo')}

Use force_text to allow translation of map attribution

---

leaflet/__init__.py

I'm getting this error for points geometries:
```
Uncaught Error: Invalid LatLng object: (NaN, NaN) 
```
after this commit: https://github.com/makinacorpus/django-leaflet/commit/c84a9a6c1c22d86690f110cc09243055415cfae6
"minzoom" is set anyway, probably with undefined, and likely causing the error in Leaflet:
https://github.com/makinacorpus/django-leaflet/blob/master/leaflet/static/leaflet/leaflet.extras.js#L49

revert MIN_ZOOM default value to 0

---

leaflet/forms/backport.py

I had to add these lines to display the form without errors, working with django-geojson.
Monkey patching: merge with care.

Fix interaction with django-geojson.

---

leaflet/templatetags/leaflet_tags.py

In newer version of django, ```debug``` option is written in the ```OPTIONS``` of ```TEMPLATES``` instead.

TEMPLATE_DEBUG has been deprecated in django 1.8

---

leaflet/forms/widgets.py
leaflet/tests/tests.py

Django does not garantee the behavior of the value and thus it should be treated defensively in the render part of the widget to prevent unnecessary exceptions.

Make sure we do not parse bad values

---

leaflet/templatetags/leaflet_tags.py
leaflet/tests/tests.py

Hello,
This pr allow to override spatial extent. Before, only the spatial extent specified in the django settings was used.
Sample use case that this pr allow
```
self.fields['geometry'].widget = LeafletWidget(attrs={
'settings_overrides': {
'SPATIAL_EXTENT': (
self.spatial_extent[0],
self.spatial_extent[1],
self.spatial_extent[2],
self.spatial_extent[3]
),
'DEFAULT_ZOOM' : None, #Zoom need to be null for fitextent
'DEFAULT_CENTER' : None, #Center need to be null for fitextent
}
})
```
**Update**
This pr change the way app_settings_overrides affect the global variable app_settings (from leaflet). Before if the above code was used, the global app_settings variable was updated with overrided values.
So every map displayed after was affected by the overrided values. I think this is a bug …

Spatial extent overrides

---

leaflet/templatetags/leaflet_tags.py

Currently in Django 1.9 there is still a `TEMPLATE_DEBUG=False` in `django.conf.global_settings` which causes the current debug detection procedure to get incorrect results if your settings comply with the new Django `TEMPLATE` settings.
This solution works in 1.9 and is backwards compatible with all previous versions.

Fix for incorrect debug detection in templatetags.leflet_js.

---

leaflet/admin.py

A simple fix to #60.
Usage for inlines is:
```python
class PoiLocationInline(LeafletGeoAdminMixin, admin.StackedInline):
model = PoiLocation
```
Depending on the maintainer's view on this, I can update the doc before merging. Maybe also create utility subclasses like `LeafletGeoStackedInline` and `LeafletGeoTabularInline`.

Move the GeoAdmin to a Mixin to allow inlines use (fix #60)

---

quicktest.py

Running tests on macOS now causes the error:
```
django.core.exceptions.ImproperlyConfigured: Unable to load the SpatiaLite library extension "/usr/local/lib/libspatialite.dylib" because: dlsym(0x7fbadca059c0, sqlite3_spatialite_init): symbol not found
```
With this patch one can run tests this way (without modifying the `quicktest.py` file itself):
```
export SPATIALITE_LIBRARY_PATH='/usr/local/lib/mod_spatialite.dylib'
python ./quicktest.py leaflet --db=sqlite
```

Use SpatiaLite library path from environment variable for running tests

---

leaflet/tests/tests.py

When STATICFILES_STORAGE is set to some complicated storage (like `django.contrib.staticfiles.storage.ManifestStaticFilesStorage`) and DEBUG is set to off, `static` templatetag might raise a ValueError complaining about non-existing file (see the attached traceback).
As a result, it is impossible for collectstatic to actually create these non-existing files, unless it is run with DEBUG=True for the first time.
This is caused by filling `PLUGINS` during app import.
The clear solution (as for me) is to replace PLUGINS dict with a class which lazily calls `static` when required. I might work on it, if you think this would be an appropriate solution.
Added a failing testcase for this.
Here is a traceback of collectstatic call (django 1.9):
```
Traceback (most recent call last):
File …
```

Unable to collectstatic with non-default STATICFILES_STORAGE

---

leaflet/static/leaflet/leaflet.forms.js

This PR reverts PR #95, which was implemented as a workaround for issue #90. It seems that Leaflet has been fixed in the meantime so that the hangup encountered in issue #90 no longer occurs. Therefore the workaround (#95) is no longer needed and this then resolves the side-effect of #95 (filed as issue #165) wherein if the geometry field to be displayed is a point, the zoom level is not the maximum (because `fitBounds()` was bypassed).

Fix #165 (zoom level is not max)

---

leaflet/templates/leaflet/_leaflet_map.html

This patch allows to store global references to leaflet map instances created in `loadmap()` in order to enable more complex customisations that require direct access to the leaflet map instances.
I couldn't find a way to do this so I've done this in my project, but I would prefer to avoid overriding the entire `_leaflet_map.html` template and having this small change included upstream instead.
Looking forward to hear feedback.
Best regards.

[JS] Allow storing global leaflet map instances

---

leaflet/templates/leaflet/js.html

It produced URLs that didn't have a slash between path and leafname, ending up with URLs like `/static/leafletmarker-icon.png`.

Fix FORCE_IMAGE_PATH option

---

.travis.yml
leaflet/locale/es/LC_MESSAGES/django.po

Fixed some words and added missing accents. Also fixed failed travis build by adding ignore W504 error on flake8 command args.
Automated build output without changes:
leaflet/admin.py:35:40: W504 line break after binary operator
The command "flake8 --ignore=E501 leaflet" failed and exited with 1 during .

Fix typo and travis build (Locale ES)

---

CHANGES
leaflet/admin.py

Fixes (for me at least) #151 
Not sure what to do if an instance is passed as the widget rather than a class, and might want to check the other fields on LeafletMap and merge them with the widget if needed (Tho some of them can be overridden in other ways).
This at least lets me use a custom geometry_field_class, so I can disable the rectangle control.

use a custom widget if one is specified

---

CHANGES
docs/templates.rst
docs/widget.rst
leaflet/static/leaflet/leaflet.css
leaflet/templates/leaflet/widget.html

Closes #247 
* Added a very long and therefore likely unique CSS class `django-leaflet-raw-textarea` to the raw textarea
* Default CSS style for `django-leaflet-raw-textarea` is width 100%
* Clarified the textarea label to specifically mention GeoJSON Geometry and added link to GeoJSONLint.com
Questions:
* Where in the docs should `display_raw` (and the resizing of the textarea) be documented?
* Should we get rid of the `cols` and `rows` attributes in the textarea?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/makinacorpus/django-leaflet/249)

Add CSS class .django-leaflet-raw-textarea to raw textarea, default width 100%

---

docs/widget.rst

This change fixes the formatting of one code block and the internal labels from my earlier PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/makinacorpus/django-leaflet/250)

Fix formatting of widget.rst

---

leaflet/__init__.py
leaflet/forms/backport.py
leaflet/templatetags/leaflet_tags.py
leaflet/tests/tests.py

According to [Django 3 release](https://docs.djangoproject.com/en/3.0/releases/3.0/) 
both `django.utils.six` and `django.contrib.staticfiles.templatetags.staticfiles.static()` are removed
This PR should fix ImportErrors

fix: Django 3.0 deprecation import fix

---

setup.py

Add 'six' into the install_requires in the setup.py. 
Related to issue #275

Require six to make django-leaflet works

---

leaflet/admin.py

That's a minor change of the default map_width for LeafletGeoAdmin

Display the map on mobile (Fixes #241)

---

docs/templates.rst
leaflet/static/leaflet/leaflet.forms.js

Fix the bug in my previous [PR](https://github.com/makinacorpus/django-leaflet/commit/d1597cfab608d555f24346cf35800e0884dcdb5a)

Bug fix: Geometry has not been displayed if geometry field name is not 'geom'

---

docs/templates.rst

you could consider adding some ``console.log`` instructions, mentioning the error in the configuration, when the above happens.
or you could replace the ``DEFAULT_ZOOM`` / ``DEFAULT_CENTER`` pair with a single ``DEFAULT_VIEW`` entry, with the same shape as the parameters for ``.setView``.  gradually, obviously, through deprecation.

document consequences of configuration error

---

leaflet/templates/leaflet/widget.html

Replace link to geojsonlint.com with geojson.io. The former is monetized with clickbait-y ads, which have been reported as inappropriate for a professional environment.
In reply to https://github.com/makinacorpus/django-leaflet/issues/297#issuecomment-666285654
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/makinacorpus/django-leaflet/298)

Update help text on map widget

---

.github/workflows/python-app.yml
CHANGES
quicktest.py
tox.ini

* Add to tox and travis grids.
* Add new setting.

Support Django 3.2 and drop Django 1.11, 2.0, and 2.1.

---

CHANGES
leaflet/forms/widgets.py
leaflet/tests/tests.py

This will deprecate [`LeafletWidget._get_attrs`](https://github.com/makinacorpus/django-leaflet/blob/e9b71ae2017689767eadbfd0db682a94c2e8d3e3/leaflet/forms/widgets.py#L33) in favor of `LeafletWidget.get_attrs` for the use in e.g. [`django.forms.MultiWidget`](https://docs.djangoproject.com/en/dev/ref/forms/widgets/#django.forms.MultiWidget).
The issue of `_get_attrs` has been discussed in #322 and should be resolved by this.

Make 'LeafletWidget._get_attrs' a public method

---

docs/widget.rst

**Problem**:
Original html code snippet in `docs/widget.rst`:
```
{% load leaflet_tags %}
<html>
<head>
{% leaflet_js plugins="forms" %}
{% leaflet_css plugins="forms" %}
</head>
<body>
<h1>Edit {{ object }}</h1>
<form action="POST">
{{ form }}
<input type="submit"/>
</form>
</body>
</html>
```
**`POST`** is a HTML form **`method`** (and not `action`) so the above snippet does not produce a valid HTML form.
**Solution**:
I propose to change **`<form action="POST">`** to **`<form method="POST">`** in the above code snippet.

fix(docs): change "action=POST" to "method=POST" in HTML snippet in docs/widget.rst

---

leaflet/admin.py
leaflet/static/leaflet/leaflet_django.css
leaflet/templates/leaflet/admin/widget.html
leaflet/tests/tests.py

From Django 4.2, map_height/map_width are deprecated and Django recommends setting the map sizes in external CSS instead.

Moved CSS and height/width to custom CSS file

---

leaflet/static/leaflet/leaflet.forms.js

this edition widget is not relevant in the context of this django admin.

remove circlemarker from leaflet draw control

---

docs/templates.rst

Thanks for both `django-geojson` and `django-leaflet`, it's really convenient to use!
In [django-geojson](https://django-geojson.readthedocs.io/en/latest/views.html#geojson-template-filter) is stated that I can simply put 
```
// Leaflet JS
L.geoJson({{ object_list|geojsonfeature|safe}}).addTo(map);
```
to add data from my queryset to a map. However, it seems to be a [bit more complicated](https://stackoverflow.com/questions/52822561/add-geojson-to-a-leaflet-map-through-the-django-template). 
I thought it might be a good idea to contribute a working solution. If you think it is correct, we might also want to update the _django-geojson_ docs or link to this page.

add django-geojson template filter to the documentation

---

.github/workflows/python-app.yml
CHANGES
quicktest.py
setup.py
tox.ini

Copied most of the approach from 35d10aadf1faabbbe465747783e14e2075c3a137. I don’t see any new warnings on Python 3.12 + Django 5.0 when running locally.

Support Django 5.0 and Python 3.12, drop Python 3.8

---

leaflet/__init__.py
leaflet/forms/widgets.py

Refs #383. Avoid `<script src="/static/leaflet/leaflet.extras.js"></script>` being rendered twice when the `forms` plugin is requested. This also fixes the syntax error since it avoids reusing `imgPathElement`, as `leaflet.extras.js` would now only be included once.

Remove forms dependency on 'extras'

---

.github/workflows/python-app.yml
CHANGES
setup.py
tox.ini

5.2 is in alpha: https://www.djangoproject.com/weblog/2025/jan/16/django-52-alpha-1-released/
Python 3.13 came out in October 2024, which is also when 3.8 went EOL.
Adapted necessary changes from #373.

Support Django 5.2 and Python 3.13, drop Python 3.8

---

leaflet/forms/widgets.py

 Solve broken marker image paths in the admin panel
